version: '3'
services:
  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    pid: host
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_SITE=datadoghq.com
     - DD_LOGS_ENABLED=true
    #  - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
     - DD_CONTAINER_EXCLUDE=name:datadog
    volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #  - /proc/:/host/proc/:ro
    #  - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    #  - /var/lib/docker/containers:/var/lib/docker/containers:ro
     - ./datadog_conf/:/conf.d/
     - magento_log:/var/log/magento
    networks:
      - datadog

volumes:
  magento_data:
    external: true

networks:
  datadog:
   name: datadog